name: Lighthouse CI
on:
  schedule:
    - cron: "0 5 1 * *" # start of month
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sitemap URL Extractor
        uses: tcarrio/sitemap-urls-extractor@1.0.0
        id: sitemap-urls
        with:
          sitemap-url: "https://www.eearomatics.com/sitemap.xml"
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: "${{ steps.sitemap-urls.outputs.urls }}"
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: 'lighthouserc.js'
